[theme]
primaryColor = "#1DB954"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
headless = true

[browser]
serverAddress = "spotify-playlist-sorter.streamlit.app"
serverPort = 443
gatherUsageStats = false